[job]
system = [ "nnodes.job", "Traverse",]
name = "Database maker"
nnodes = 2
account = "GEO111"
walltime = 180.0
gap = 50.0
debug = true

[root]
task = [ "workflow", "main",]
workflowname = "Making a database right now, yeaah!"
db = "/scratch/gpfs/lsawade/SpecfemMagicGF/DB_forward_test"
station_file = "stations.txt"
creation = false
simulation = false
processing = true
clear = false

[root.cfg]
specfemdir = "/scratch/gpfs/lsawade/SpecfemMagicGF/specfem3d_globe"
par_file = "/scratch/gpfs/lsawade/SpecfemMagicGF/DATA_default/Par_file"
target_file = "/scratch/gpfs/lsawade/SpecfemMagicGF/workflow/GF_LOCATIONS_single_element"
target_latitude = 35.03
target_longitude = 26.85
target_depth = 24.0
element_buffer = 0
t0 = 0.0
tc = 200.0
duration_in_min = 60.0
ndt = 5.0
lpfilter = "butter"
subsample = true
force_factor = 10000000000.0
forward_test = true
cmtsolutionfile = "/scratch/gpfs/lsawade/SpecfemMagicGF/workflow/CMTSOLUTION"
broadcast_mesh_model = false
simultaneous_runs = false
overwrite = false

[root.processparams]
precision = "half"
compression = "None"
