[job]
system = [ "nnodes.job", "Traverse",]
name = "Database maker"
nnodes = 2
account = "GEO111"
walltime = 180.0
gap = 50.0
debug = true

[root]
task = [ "workflow", "main",]
workflowname = "Making a database right now, yeaah!"
db = "/gpfs/alpine/geo111/scratch/lsawade/DB/GLAD-M25/128/"
station_file = "stations_BFO.txt"
creation = false
simulation = false
processing = true
clear = false

[root.cfg]
specfemdir = "/gpfs/alpine/geo111/scratch/lsawade/RECIPROCAL_SPECFEMS/GLAD-M25/128/specfem3d_globe_reciprocal"
par_file = "../DATA_default/Par_file"
target_file = "../DATA_default/GF_LOCATIONS"
target_latitude = 35.03
target_longitude = 26.85
target_depth = 24.0
element_buffer = 1
t0 = 0.0
tc = 200.0
duration_in_min = 240.0
ndt = 4.0
lpfilter = "butter"
subsample = true
force_factor = 10000000000.0
cmtsolutionfile = "../DATA_default/CMTSOLUTION"
broadcast_mesh_model = false
simultaneous_runs = false
overwrite = false
forward_test = true
forwardoutdir = "/gpfs/alpine/geo111/scratch/lsawade/RECIPROCAL_SPECFEMS/GLAD-M25/128/specfem3d_globe"

[root.processparams]
precision = "half"
compression = "None"
