[job]
system = [ "nnodes.job", "Frontier",]
name = "Database maker"
nnodes = 12
account = "GEO111"
walltime = 120.0
gap = 25.0
debug = false

[root]
task = [ "workflow", "main",]
workflowname = "Making a database right now, yeaah!"
db = "/lustre/orion/geo111/scratch/lsawade/DB/GLAD-M35/256_TEST"
station_file = "stations_BFO.txt"
creation = true
simulation = true
processing = true
clear = false
forward_test = true
cmtsolutionfile = "../DATA_default/CMTSOLUTION"
forward_specfem = "/lustre/orion/geo111/scratch/lsawade/packages/sf3dgf/8.0/GLAD-M35-256x256"

[root.cfg]
specfemdir = "/lustre/orion/geo111/scratch/lsawade/packages/sf3dgr/8.0/GLAD-M35-256x256"
par_file = "../DATA_default/Par_file"
target_file = "../DATA_default/GF_LOCATIONS_FULL_GCMT_CATALOG"
target_latitude = 35.03
target_longitude = 26.85
target_depth = 24.0
element_buffer = 1
t0 = 0.0
tc = 200.0
duration_in_min = 240.0
ndt = 4.0
lpfilter = "butter"
subsample = true
force_factor = 100000000000000.0
cmtsolutionfile = "../DATA_default/CMTSOLUTION"
broadcast_mesh_model = false
simultaneous_runs = false
overwrite = false
forward_test = false
# forwardoutdir = null

[root.processparams]
precision = "single"
compression = "None"
