[MAIN]
MODULE_PATH="/ccs/home/lsawade/Modules/modulefiles"
PACKAGE_DIR="/lustre/orion/geo111/scratch/lsawade/packages"

[SPECFEM]
FORWARD=true
RECIPROCAL=false
VERSION="8.0"
TAG="GLAD-M35-256x256-SHAKEMOVIE"
LINK="git@github.com:SPECFEM/specfem3d_globe.git"
DATA_default="DATA_M35_SHAKEMOVIE"
BRANCH="devel"
RECIPROCAL_EXTERNAL_STF=true
ASDF=false
ADIOS=true
GPU='HIP'


# IF THE PAR_FILES model paramater is set to 'GLL', then the model_gll_location will
# copy the given model to the directory and use it for the compilation.
# If empty or model is not GLL it is ignored.
model_gll_location='/lustre/orion/proj-shared/geo111/models2/m35.bp' # Keep empty if you∑
#/lustre/orion/geo111/scratch/lsawade/packages/hdf5/1.12.3/install

# CUDA: cuda<#> | HIP: MI<XXX>
GPU_VERSION='MI250'

# Depending on GPU, sets HIPFLAGS or CUDAFLAGS
GPU_FLAGS='--amdgpu-target=gfx90a -fPIC -ftemplate-depth-2048 -O3 -fdenormal-fp-math=ieee -fcuda-flush-denormals-to-zero -munsafe-fp-atomics -fno-gpu-rdc -g'

# Use this to Update any parameter for the forward par_file parameters
[SPECFEM.Par_file.FORWARD]
MODEL='GLL'

# Use this to Update any parameter for the reciprocal par_file parameters
[SPECFEM.Par_file.RECIPROCAL]
MODEL='GLL'

# Use this to set the necessary environment variables for setup and compilation
# Empty if not needed to be set.
[ENV]
SF3DGF=''
SF3DGR=''
CC=''
CXX=''
MPICC=''
MPICXX=''
FC=''
MPIFC=''
CFLAGS='-g -fallow-argument-mismatch -O2 -pthread'
CXXFLAGS=''
FCFLAGS=''
ADIOS_VERSION=''
ADIOS_INSTALL=''
HDF5_ROOT=''
